mailcatcher:
  image: schickling/mailcatcher
  ports:
    - 1025:1025
    - 1080:1080
postgres:
  image: postgres:9.6
  ports:
    - 54320:5432
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
redis:
  image: redis
  ports:
    - 63790:6379
