version: '3'
services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/commie
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - mailcatcher

